// Saturday Album Club listening history.
// One object per Saturday, from the start of the series through 2026-08-29.

const albumHistory = [
  {
    date: "2023-11-25",
    person: null,
    artist: "Paul Pena",
    album: "self titled",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2023-12-02",
    person: null,
    artist: "Stevie Ray Vaughn and Double Trouble",
    album: "Texas Flood",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2023-12-09",
    person: null,
    artist: "Paul Simon",
    album: "Graceland",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2023-12-16",
    person: null,
    artist: "",
    album: "Stand By Me",
    notes: "soundtrack",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2023-12-23",
    person: null,
    artist: "Wilco",
    album: "Sky Blue Sky",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2023-12-30",
    person: "Marshall",
    artist: "ABB",
    album: "Eat a Peach",
    notes: "Video presentation from Marshall",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-01-06",
    person: null,
    artist: "",
    album: "",
    notes: "slipped up and skipped due to holiday commotion",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-01-14",
    person: null,
    artist: "Black Sabbath",
    album: "Paranoid",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-01-20",
    person: null,
    artist: "The Band",
    album: "Stage Fright",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-01-27",
    person: null,
    artist: "Jurassic 5",
    album: "Quality Control",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-02-03",
    person: null,
    artist: "Tom Petty & the Heartbreakers",
    album: "Into the Great Wide Open",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-02-10",
    person: null,
    artist: "Delbert McClinton",
    album: "Live from Austin",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-02-17",
    person: null,
    artist: "Neal Francis",
    album: "Changes",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-02-24",
    person: null,
    artist: "Grady Spencer & The Work",
    album: "Wait",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-03-02",
    person: null,
    artist: "Uncle Tupelo",
    album: "No Depression",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-03-09",
    person: null,
    artist: "The Meters",
    album: "Rejuvenation",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-03-16",
    person: null,
    artist: "Flaming Lips",
    album: "Soft Bulletin",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-03-23",
    person: null,
    artist: "The Who",
    album: "Who’s Next",
    notes: "PPP",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-03-30",
    person: null,
    artist: "Ricky Skaggs & Bruce Hornsby",
    album: "Ricky Skaggs & Bruce Hornsby",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-04-06",
    person: null,
    artist: "War",
    album: "All Day Music",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-04-13",
    person: null,
    artist: "The Marshall Tucker Band",
    album: "The Marshall Tucker Band",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-04-20",
    person: null,
    artist: "ABB",
    album: "Shades of Two Worlds",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-04-27",
    person: null,
    artist: "Sam Cooke",
    album: "Live at Harlem Square",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-05-04",
    person: null,
    artist: "Sturgill Simpson",
    album: "Metamodern Sounds in Country Music",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-05-11",
    person: null,
    artist: "Sam Bush",
    album: "Glamour and Grits",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-05-18",
    person: null,
    artist: "Jeff Buckley",
    album: "Grace",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-05-25",
    person: null,
    artist: "Widespread Panic",
    album: "Light Fuse, Get Away",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-06-01",
    person: null,
    artist: "Dan Auerbach",
    album: "Waiting on a Song",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-06-08",
    person: null,
    artist: "The New Mastersounds",
    album: "Shake It",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-06-15",
    person: null,
    artist: "The Wood Brothers",
    album: "Live at the Barn",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-06-22",
    person: null,
    artist: "Bob Marley",
    album: "Natty Dread",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-06-29",
    person: null,
    artist: "Allison Krauss and Union Station",
    album: "Lonely Runs Both Ways",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-07-06",
    person: null,
    artist: "Old Crow Medicine Show",
    album: "50 Years of Blonde on Blonde- Live",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-07-13",
    person: null,
    artist: "Billy Strings",
    album: "Billy Strings Live vol. 1",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-07-20",
    person: null,
    artist: "John Prine",
    album: "John Prine",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-07-27",
    person: null,
    artist: "Tyler Childers",
    album: "Live on Red Barn Radio I and II",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-08-03",
    person: null,
    artist: "Jack White",
    album: "No Name",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-08-10",
    person: null,
    artist: "Shinyribs",
    album: "Well After Awhile",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-08-17",
    person: null,
    artist: "Silk Sonic",
    album: "An Evening with Silk Sonic",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-08-24",
    person: null,
    artist: "The Beatles",
    album: "Let It Be",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-08-31",
    person: null,
    artist: "The Chicks",
    album: "Home",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-09-07",
    person: null,
    artist: "Talking Heads",
    album: "Stop Making Sense",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-09-14",
    person: null,
    artist: "Beastie Boys",
    album: "License to ill",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-09-21",
    person: null,
    artist: "Aretha Franklin",
    album: "This Girls in Love With You",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-09-28",
    person: null,
    artist: "Crosby, Stills & Nash",
    album: "self-titled",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-10-05",
    person: null,
    artist: "My Morning Jacket",
    album: "Z",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-10-12",
    person: null,
    artist: "Lyle Lovett",
    album: "Pontiac",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-10-19",
    person: null,
    artist: "Dolly Parton",
    album: "The Grass is Blue",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-10-26",
    person: null,
    artist: "Red Clay Strays",
    album: "Made by These Moments",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-11-02",
    person: null,
    artist: "Grateful Dead",
    album: "Fallout from the Phil Zone",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-11-09",
    person: null,
    artist: "Drive by Truckers",
    album: "The Dirty South",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-11-16",
    person: null,
    artist: "B.B. King",
    album: "Live at The Regal",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-11-23",
    person: null,
    artist: "Hiss Golden Messenger",
    album: "Sanctuary Songs",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-11-30",
    person: null,
    artist: "St. Paul and the Broken Bones",
    album: "Half The City",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-12-07",
    person: null,
    artist: "Pearl Jam",
    album: "Ten",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-12-14",
    person: null,
    artist: "Waylon Jennings",
    album: "Honky Tonk Heroes",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-12-21",
    person: null,
    artist: "Pink Floyd",
    album: "Wish You Were Here",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2024-12-28",
    person: null,
    artist: "Allen Toussaint",
    album: "Sweet Touch of Love",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-01-04",
    person: null,
    artist: "Jim Croce",
    album: "You Don’t Mess Around With Jim",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-01-11",
    person: null,
    artist: "Billy Preston",
    album: "The Best",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-01-18",
    person: null,
    artist: "Johnny Jenkins",
    album: "Ton-Ton Macoute!",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-01-25",
    person: null,
    artist: "Ry Cooder",
    album: "Paradise and Lunch",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-02-01",
    person: null,
    artist: "The Rolling Stones",
    album: "Exile on Main Street",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-02-08",
    person: null,
    artist: "John Mayer",
    album: "Continuum",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-02-15",
    person: null,
    artist: "R.E.M",
    album: "Document",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-02-22",
    person: null,
    artist: "Pretenders",
    album: "Learning to Crawl",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-03-01",
    person: "Anne Mar",
    artist: "Turnpike Troubadours",
    album: "Goodbye Normal Street",
    notes: "guest curator",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-03-08",
    person: null,
    artist: "Eric Clapton",
    album: "Slowhand",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-03-15",
    person: null,
    artist: "Acoustic Syndicate",
    album: "Live From The Neighborhood",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-03-22",
    person: null,
    artist: "The Traveling Wilburys",
    album: "Vol. 1",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-03-29",
    person: null,
    artist: "Neil Young",
    album: "On the Beach",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-04-05",
    person: null,
    artist: "Black Crowes",
    album: "The Southern Harmony and Musical Companion",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-04-12",
    person: null,
    artist: "Tedeschi Trucks Band",
    album: "I Am The Moon: IV. Farewell",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-04-19",
    person: null,
    artist: "Jimmy Buffett",
    album: "Living and Dying in 3/4 Time",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-04-26",
    person: null,
    artist: "James Taylor",
    album: "Greatest Hits",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-05-03",
    person: null,
    artist: "Galactic",
    album: "Ruckus",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-05-10",
    person: null,
    artist: "Led Zeppelin",
    album: "Led Zeppelin IV",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-05-17",
    person: null,
    artist: "The Heavy Heavy",
    album: "One of a Kind",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-05-24",
    person: null,
    artist: "Credence Clearwater Revival",
    album: "Cosmo’s Factory",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-05-31",
    person: null,
    artist: "Albert King",
    album: "I’ll Play the Blues For You",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-06-07",
    person: null,
    artist: "Lynyrd Skynyrd",
    album: "Second Helping",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-06-14",
    person: null,
    artist: "Phish",
    album: "Farmhouse",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-06-21",
    person: null,
    artist: "Jerry Jeff Walker",
    album: "Viva Terlingua",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-06-28",
    person: null,
    artist: "The Undisputed Truth",
    album: "The Undisputed Truth",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-07-05",
    person: null,
    artist: "Tower of Power",
    album: "Tower of Power",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-07-12",
    person: null,
    artist: "Robert Earl Keen",
    album: "Best",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-07-19",
    person: null,
    artist: "Steely Dan",
    album: "Aja",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-07-26",
    person: null,
    artist: "Willie Nelson",
    album: "Red Headed Stranger",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-08-02",
    person: null,
    artist: "Avett Brothers",
    album: "I and Love and You",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-08-09",
    person: null,
    artist: "Jerry Garcia, David Grisman, Tony Rice",
    album: "The Pizza Tapes",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-08-16",
    person: null,
    artist: "Leftover Salmon",
    album: "The Nashville Sessions",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-08-23",
    person: null,
    artist: "Sam Cooke",
    album: "Night Beat",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-08-30",
    person: null,
    artist: "Bob Dylan",
    album: "Nashville Skyline",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-09-06",
    person: null,
    artist: "Nickel Creek",
    album: "Nickel Creek",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-09-13",
    person: null,
    artist: "Dave Matthews Band",
    album: "Recently",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-09-20",
    person: null,
    artist: "Taj Mahal",
    album: "The Natch’l Blues",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-09-27",
    person: null,
    artist: "Beck",
    album: "Sea Change",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-10-04",
    person: null,
    artist: "Rick Danko",
    album: "Live on Breeze Hill",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-10-11",
    person: null,
    artist: "Waylon Jennings",
    album: "Songbird",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-10-18",
    person: null,
    artist: "Widespread Panic",
    album: "Ain’t Life Grand",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-10-25",
    person: null,
    artist: "Rush",
    album: "Farewell to Kings",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-11-01",
    person: null,
    artist: "Guns N’ Roses",
    album: "Appetite for Destruction",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-11-08",
    person: null,
    artist: "Cordovas",
    album: "That Santa Fe Channel",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-11-15",
    person: null,
    artist: "Guy Clark",
    album: "Old No. 1",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-11-22",
    person: null,
    artist: "Alice In Chains",
    album: "Unplugged",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-11-29",
    person: null,
    artist: "Jimmy Cliff",
    album: "Best of Jimmy Cliff",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-12-06",
    person: null,
    artist: "Gov’t Mule",
    album: "Live From Roseland Ballroom",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-12-13",
    person: null,
    artist: "Reigning Sound",
    album: "Shattered",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-12-20",
    person: null,
    artist: "AC/DC",
    album: "Back In Black",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2025-12-27",
    person: null,
    artist: "Blue Dogs",
    album: "Live @ The Dock St. Theater",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-01-03",
    person: null,
    artist: "Emma Gibbs Band",
    album: "Out to the Country",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-01-10",
    person: null,
    artist: "Bob Weir",
    album: "Ace",
    notes: "RIP",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-01-17",
    person: null,
    artist: "Traffic",
    album: "Traffic",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-01-24",
    person: null,
    artist: "The California Honeydrops",
    album: "Call it Home, Vol. 1",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-01-31",
    person: null,
    artist: "Ray Charles",
    album: "Genius Loves Company",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-02-07",
    person: "Leigh",
    artist: "The Rolling Stones",
    album: "Goats Head Soup",
    notes: "guest picker",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-02-14",
    person: null,
    artist: "Radiohead",
    album: "OK Computer",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-02-21",
    person: null,
    artist: "Fleetwood Mac",
    album: "Rumours",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-02-28",
    person: null,
    artist: "Red Hot Chili Peppers",
    album: "Californication",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-03-07",
    person: null,
    artist: "Big Head Todd and The Monsters",
    album: "Sister Sweetly",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-03-14",
    person: null,
    artist: "Col. Bruce Hampton & The Aquarium Rescue Unit",
    album: "self titled",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-03-21",
    person: null,
    artist: "Band of Horses",
    album: "Cease to Begin",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-03-28",
    person: null,
    artist: "The Dip",
    album: "The Dip",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-04-04",
    person: null,
    artist: "Jason Isbell and The 400 Unit",
    album: "The Nashville Sound",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-04-11",
    person: null,
    artist: "Trigger Hippy",
    album: "Trigger Hippy",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-04-18",
    person: null,
    artist: "Ann Peebles",
    album: "Straight from the Heart",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-04-25",
    person: null,
    artist: "ZZ Top",
    album: "Tres Hombres",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-05-02",
    person: null,
    artist: "Cymande",
    album: "Cymande",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-05-09",
    person: null,
    artist: "Leon Bridges",
    album: "Coming Home",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-05-16",
    person: null,
    artist: "J and The Causeways",
    album: "Live at Tipitina’s",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-05-23",
    person: null,
    artist: "The Byrds",
    album: "Sweetheart of the Rodeo",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-05-30",
    person: null,
    artist: "American Aquarium",
    album: "Live at Red Rocks",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-06-06",
    person: null,
    artist: "Lowell George",
    album: "Thanks I’ll Eat it Here",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-06-13",
    person: null,
    artist: "Sturgill Simpson",
    album: "Cuttin’ Grass - Vol. 1",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-06-20",
    person: null,
    artist: "The Big Chill",
    album: "Soundtrack",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-06-27",
    person: null,
    artist: "Professor Longhair",
    album: "Live On The Queen Mary",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-07-04",
    person: null,
    artist: "The Grateful Dead",
    album: "Crimson, White & Indigo",
    notes: "🇺🇸🗽🎇",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-07-11",
    person: null,
    artist: "The Velvet Underground",
    album: "Loaded",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-07-18",
    person: null,
    artist: "Stevie Wonder",
    album: "Innervisions",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-07-25",
    person: null,
    artist: "Breakfield",
    album: "self-titled",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-08-01",
    person: null,
    artist: "Hard Working Americans",
    album: "self-titled",
    notes: "",
    writeup: "",
    coverUrl: "",
  },
  {
    date: "2026-08-08",
    person: "Sean",
    artist: "Van Halen",
    album: "Van Halen I",
    notes: "",
    writeup: "",
    coverUrl: "https://upload.wikimedia.org/wikipedia/en/0/0d/Van_Halen_album.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail_unscaled",
  },
  {
    date: "2026-08-15",
    person: "Casey",
    artist: "The Replacements",
    album: "All Shook Down",
    notes: "",
    writeup: "",
    coverUrl: "https://upload.wikimedia.org/wikipedia/en/8/8c/The_Replacements_-_All_Shook_Down_cover.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail_unscaled",
  },
  {
    date: "2026-08-22",
    person: "Jeremy",
    artist: "Sammy Kershaw",
    album: "Politics, Religion and Her",
    notes: "",
    writeup: `Last week’s pick from Casey got me thinking about the ’90s, and it made me realize there’s a pretty significant hole in our Saturday Album Series. One that probably represents the bulk of my music catalog. 

For me, the 90’s was a turning point. I spent a lot of my teenage years buried in ’90s alternative, and then somewhere along the way I heard George Strait’s Blue Clear Sky. That song—and that album—somehow snapped me out of it and started what has turned into a decades-long love affair with country music.

But tonight isn’t George Strait.

I wanted to go a little deeper into that ’90s country world, and I wanted something with a little less slow tear jerkers. This album opens with what I’d consider the top five most singable party country songs of all time. Followed by the top charting single from this album that is still beltable. 

And that’s really why I picked this one. It’s not necessarily the most obvious or critically acclaimed album from the era, but it captures a version of country music that was everywhere when we were growing up—and one that I think we’ve largely skipped over in this series.

So, Casey got us thinking about the ’90s.

Tonight, we’re finally giving the decade its proper country treatment.

Hope yall enjoy Sammy Kershaw — Politics, Religion and Her. (Also a great song on the album)`,
    coverUrl: "https://upload.wikimedia.org/wikipedia/en/a/af/Politics%2CReligionandHer.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail_unscaled",
  },
  {
    date: "2026-08-29",
    person: "Brian",
    artist: "Dolly Parton",
    album: "The Complete Trio Collection",
    notes: "",
    writeup: `About a month ago, I was watching a CNN documentary on Linda Ronstadt and I decided to add her name to my list of potentials for our Saturday Album Club.  Later in the documentary, I learned that Linda, Dolly and Emmylou had done a couple of albums together, and Emmylou was already on my list of potentials. Their album was then added to my list as well, as that is an All-Star trio.  

Then, earlier this week, Dolly passes and it seems like the obvious choice to select as a tribute to her amazing voice and life.  I particularly love the cover they do of Neil Young’s “After the Gold Rush”.  

RIP Dolly.  Thanks for living a life that made a positive impact on this world.

(This is a compilation of their music and runs over 2 hours, so feel free to skip around and enjoy the ones that you prefer.  They are all pretty damn enjoyable.)

(Fun side note: SAC alum, Ry Cooder, is also interviewed in the Linda Ronstadt documentary.  It is worth checking out.)`,
    coverUrl: "https://www.dollydiscography.com/uploads/4/5/9/1/4591011/complete-trio-fotor_orig.jpg",
  },
  {
    date: "2026-09-05",
    person: "Bagley",
    artist: "Brute",
    album: "Co-balt",
    notes: "",
    writeup:
      "Evening gents. For my second SAC pick in a row, we will have Mr Schools featured on bass. But this time he will be joined by the rest of the classic Panic lineup. Tonight we will hear the second album from the side project they did with Vic Chesnutt, released just four months before we lost the great Mikey. This second album is much stronger, in my opinion, than the debut they did several years prior to this one. You’ll recognize the classic Panic sound from the first note of the first song. \nAll songs were written by Vic, and let’s just say some of his lyrics are, um, interesting. In particular, All Kinds has some unique lyrics. You may want to turn that one down if your significant other is nearby.\nHope y’all enjoy another great Athens, GA band, brute., and their final album Co-Balt.",
    coverUrl: "https://wranglerspace.s3-accelerate.amazonaws.com/2002/04/Cobalt.jpg",
  },
];
